# Base configuration for daemon
# This file contains default settings that apply to all environments

stream:
  id: 1
  pg_connection:
    host: "localhost"
    port: 5432
    name: "postgres"
    username: "postgres"
    tls:
      enabled: false
      trusted_root_certs: ""
  batch:
    max_size: 100
    max_fill_ms: 50

sink:
  type: memory

