stream:
  id: 1
  pg_connection:
    host: "localhost"
    port: 5432
    name: "postgres"
    username: "postgres"
    password: null
    tls:
      enabled: false
      trusted_root_certs: ""
  batch:
    max_size: 1000
    max_fill_ms: 1000

sink:
  type: memory

